# Packages ---- 

# Apply function
install_load(c("rio", 
               "janitor", 
               "tidyverse", 
               "openxlsx",
               "chilemapas", 
               "patchwork",
               "sf", 
               "vtable",
               "naniar", 
               "visdat", 
               "parallel", 
               "profvis", 
               "htmlwidgets",
               "future", 
               "purrr", 
               "furrr",
               "future.apply", 
               "zoo",
               "splines",      
               "magrittr",
               "plotly",      
               "nlme",
               "ggstatsplot",
               "tidymodels",
               "knitr", 
               "kableExtra"
               ))
